version: '3.8'
services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_MODELS=qwen:latest
  # Optional: logging agent (e.g., Vector)
  logging-agent:
    image: timberio/vector:latest
    ports:
      - "8686:8686"
    command: ["vector", "--config", "/etc/vector/vector.toml"]
    volumes:
      - ./vector.toml:/etc/vector/vector.toml:ro
    depends_on:
      - ollama
volumes:
  ollama_data:
